### PR TITLE
remove `enabled` frome events

### LINKED ISSUE #15: remove "enabled"
can we remove this field in the config? would anyone has an event and disable it?

### PR DESCRIPTION
**Pull request by sixinli**
-notice that the top level one is still around
-this fixes #15

### CODE REVIEW

**Comment by zoubeiri** [comment]
I think putting this in was a request from Geoff. What's the rationale for removing this?

**Comment by gscshoyru** [comment]
The request was pointed at the land of the event logger, where there was no way to extend it and no way to disable a specific event type in the same block. But with web-logger, if you don't put the event type in the list, it won't get logged. So... this sufficiently serves the purpose of disabling the logging of a given type (since we can also detect whether or not a specific event name is in the list or not). 

I'm not sure we _need_ to remove this, though -- but it's certainly not necessary to have.

**Comment by sixinli** [comment]
we dont have to remove it... but just thinking that the use of it would probably be rare

**Comment by sixinli** [comment]
Closed by https://github.com/palantir/dropwizard-web-logger/pull/19.

**Pull request closed without merging**
