### PR TITLE
change logContent to take json object

### PR DESCRIPTION
**Pull request by sixinli**

### CODE REVIEW

**Comment by zoubeiri** [comment]
Running into a problem when manually testing this. We can go over it at some point today

**Comment by sixinli** [comment]
so... things are kind of weird... sending it with `"{\"A\":3}"` works (the server is getting it as `{"A":3}`) and sending it with `{"A":3}` (the server is getting is as `{A:3}` doesnt work (there's probably an extra parse somewhere)... regardless, Map<String,Object> should be sufficient, or fine as it is

**Comment by qinfchen** [comment]
What is the problem with logging the string in the original code?

**Comment by qinfchen** [comment]
@sixinli, is this still relevant?

**Comment by sixinli** [comment]
sorry not that much anymore :( , it would be nice to change the string parameter to a map, but that's minor and besides that i dont think we could change the parameter type to JsonObject

**Pull request closed without merging**
