### PR TITLE
sub second logging

### PR DESCRIPTION
**Pull request by sixinli**
moving from fork PR https://github.com/palantir/dropwizard-web-logger/pull/44/files

### CODE REVIEW

**Comment by sixinli** [comment]
good to go? @qinfchen @zoubeiri

**Comment by qinfchen** [comment]
Lgtm

Sent from my iPhone

On Jan 6, 2017, at 7:30 PM, sixinli <notifications@github.com<mailto:notifications@github.com>> wrote:


good to go? @qinfchen[github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_qinfchen&d=DwMCaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=2LK6Jot8d42Knk04ei1_FPh1f_GvosvCO-13ihGNoi8&m=ZC3kSKnM4CDFsV701Wb_XnI-puZmH0ElLLxa_hIn1cU&s=rdrb_39kGiIdHlCAvf4UUXdpHwK9gzjD-r4lLq_fUFQ&e=> @zoubeiri[github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_zoubeiri&d=DwMCaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=2LK6Jot8d42Knk04ei1_FPh1f_GvosvCO-13ihGNoi8&m=ZC3kSKnM4CDFsV701Wb_XnI-puZmH0ElLLxa_hIn1cU&s=ZYTCviS9zav8ElHLXhiNx4sQjDxIdx00P6mYG3CR0Og&e=>

**Comment by zoubeiri** [comment]
Just made a release with this change included :)

**Comment by acolombi** [comment]
Sweet! @sixinli , any chance we can get this update in a near future version of Slate?

**Pull request merged**
